language: python
python:
  - "2.7"
  - "3.5"

before_script: 
  - "sudo add-apt-repository ppa:mc3man/trusty-media -y"
  - "sudo apt-get update -y"
  - "sudo apt-get install ffmpeg -y"
  - "sudo apt-get install frei0r-plugins -y"

install: 
  - "pip install irs"

script:
  - python tests/song.py
  - python tests/album.py
  - python tests/playlist.py