language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - python setup.py install

script:
  - python tests/album.py
  - python tests/playlist.py
  - python tests/post_processors.py
  - python tests/song.py
