language: python
python:
  - "2.7"
  - "3.5"

before_script: 
  - sudo apt-get purge libav-tools
  - sudo aptitude -y -q install ffmpeg

install: 
  - "pip install irs"

script:
  - python tests/song.py
  - python tests/album.py
  - python tests/playlist.py